export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_ONE = 'FETCH_ONE'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
export const MODAL = 'MODAL'
